### ISSUE TITLE
Card updates not being sent to the right channels

### ISSUE THREAD

**Issue by Uhsleep** [trello-talk/Taco#175]
I have 3 webhooks with different filter settings. Two have a whitelist filter type that check for updates on two different Trello lists. The last one has a blacklist filter type that checks for updates on everything but those two lists.

Updating the card titles and descriptions work as intended. However, things like updating checklists, commenting, members watching a card, etc. always have the updates sent to the wrong channels regardless of which list the card is in. Coincidentally, the updates always get sent by the webhooks that have the whitelist filtering and are always ignored by the blacklist filtered webhook.

Not sure if this is a bug due to how the filtering is done or if I'm just missing some type of functionality that'll make this work.

**Comment by Snazzah** [comment]
Seems like the webhook data for those specific card events don't show what list they are on in their webhook events. I can't really fix this without some sort of caching system that I haven't thought of yet. I know this pretty much makes list filtering have no real point, so i'll put this down as a priority and make a caching system for these types of events.
