### ISSUE TITLE
Increase card description length limit

### ISSUE THREAD

**Issue by numinit** [trello-talk/Taco#510]
We have some very long cards. Is there any way to increase the length limit for card descriptions?

**Comment by Snazzah** [comment]
No, since Discord has a limit on how long text can be.

**Comment by numinit** [comment]
I guess what I'm wondering is:

https://github.com/trello-talk/Taco/blob/master/src/commands/viewing/card.js#L47

Seems to limit the description to 2048 long, but Discord limits embeds to 4096 characters. Would there be a way to increase this? Want to figure out how realistic that is before I submit a PR.

**Comment by Snazzah** [comment]
The embed description was bumped up a bit ago, but the character limit for the whole embed is 6000 characters, not sure if I want to raise that and deal with more errors along the way. Besides, this version of Taco is being rewritten, so I may look into this on the rewrite instead.
